spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: pass1234
  cache:
    cache-names: menus_cache
  flyway:
    enabled: true
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
vhr:
  video:
    path: D:\projects\vhr\vhr\video_files\
contract:
  upload:
    path: D:\projects\vhr\vhr\contract_files\